set-option -g default-shell /bin/bash
set -g mouse on
set -g history-limit 50000

# remap prefix from 'C-b' to 'C-Space'
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

unbind '"'
unbind %
bind _ split-window -h
bind - split-window -v

# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'

run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux
set -g @resurrect-dir '~/.tmux/resurrect'
run-shell ~/.tmux/plugins/tmux-continuum/continuum.tmux
set -g @continuum-restore 'on'

#set -g status-right 'Continuum status: #{continuum_status}'
